// Code generated by "stringer --type=Quotes --output=quotes.strings.go"; DO NOT EDIT.

package quotes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Single-1]
	_ = x[Double-2]
}

const _Quotes_name = "NoneSingleDouble"

var _Quotes_index = [...]uint8{0, 4, 10, 16}

func (i Quotes) String() string {
	if i >= Quotes(len(_Quotes_index)-1) {
		return "Quotes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Quotes_name[_Quotes_index[i]:_Quotes_index[i+1]]
}
