// Code generated by "stringer -type=Word -output=keywords.strings.go"; DO NOT EDIT.

package keywords

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SELECT-0]
	_ = x[FROM-1]
	_ = x[WHERE-2]
	_ = x[LIMIT-3]
	_ = x[OFFSET-4]
	_ = x[CREATE-5]
	_ = x[TABLE-6]
	_ = x[PRIMARY-7]
	_ = x[KEY-8]
	_ = x[UNIQUE-9]
	_ = x[REFERENCES-10]
	_ = x[INDEX-11]
	_ = x[CONSTRAINT-12]
	_ = x[FOREIGN-13]
	_ = x[NULL-14]
	_ = x[DEFAULT-15]
	_ = x[IS-16]
	_ = x[NOT-17]
	_ = x[DISTINCT-18]
	_ = x[GROUP-19]
	_ = x[BY-20]
	_ = x[WITH-21]
	_ = x[HAVING-22]
	_ = x[INNER-23]
	_ = x[LEFT-24]
	_ = x[OUTER-25]
	_ = x[JOIN-26]
	_ = x[CROSS-27]
	_ = x[VIEW-28]
	_ = x[DATABASE-29]
	_ = x[USER-30]
	_ = x[AS-31]
	_ = x[SCHEMA-32]
	_ = x[IF-33]
	_ = x[EXISTS-34]
	_ = x[CHECK-35]
	_ = x[COLLATE-36]
	_ = x[BOOLEAN-37]
	_ = x[FLOAT-38]
	_ = x[REAL-39]
	_ = x[DOUBLE-40]
	_ = x[SMALLINT-41]
	_ = x[INT-42]
	_ = x[INTEGER-43]
	_ = x[BIGINT-44]
	_ = x[VARCHAR-45]
	_ = x[CHAR-46]
	_ = x[CHARACTER-47]
	_ = x[UUID-48]
	_ = x[DATE-49]
	_ = x[TIMESTAMP-50]
	_ = x[TIME-51]
	_ = x[INTERVAL-52]
	_ = x[REGCLASS-53]
	_ = x[TEXT-54]
	_ = x[BYTEA-55]
	_ = x[NUMERIC-56]
	_ = x[DECIMAL-57]
	_ = x[DEC-58]
	_ = x[ON-59]
	_ = x[DELETE-60]
	_ = x[UPDATE-61]
	_ = x[RESTRICT-62]
	_ = x[CASCADE-63]
	_ = x[SET-64]
	_ = x[ACTION-65]
	_ = x[NO-66]
}

const _Word_name = "SELECTFROMWHERELIMITOFFSETCREATETABLEPRIMARYKEYUNIQUEREFERENCESINDEXCONSTRAINTFOREIGNNULLDEFAULTISNOTDISTINCTGROUPBYWITHHAVINGINNERLEFTOUTERJOINCROSSVIEWDATABASEUSERASSCHEMAIFEXISTSCHECKCOLLATEBOOLEANFLOATREALDOUBLESMALLINTINTINTEGERBIGINTVARCHARCHARCHARACTERUUIDDATETIMESTAMPTIMEINTERVALREGCLASSTEXTBYTEANUMERICDECIMALDECONDELETEUPDATERESTRICTCASCADESETACTIONNO"

var _Word_index = [...]uint16{0, 6, 10, 15, 20, 26, 32, 37, 44, 47, 53, 63, 68, 78, 85, 89, 96, 98, 101, 109, 114, 116, 120, 126, 131, 135, 140, 144, 149, 153, 161, 165, 167, 173, 175, 181, 186, 193, 200, 205, 209, 215, 223, 226, 233, 239, 246, 250, 259, 263, 267, 276, 280, 288, 296, 300, 305, 312, 319, 322, 324, 330, 336, 344, 351, 354, 360, 362}

func (i Word) String() string {
	if i >= Word(len(_Word_index)-1) {
		return "Word(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Word_name[_Word_index[i]:_Word_index[i+1]]
}
