// Code generated by "stringer --type=Type --output=type.strings.go"; DO NOT EDIT.

package whitespace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Space-1]
	_ = x[Tab-2]
	_ = x[Newline-3]
}

const _Type_name = "UnknownSpaceTabNewline"

var _Type_index = [...]uint8{0, 7, 12, 15, 22}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
