// Code generated by "stringer -type=Word -output=keywords.strings.go"; DO NOT EDIT.

package keywords

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SELECT-0]
	_ = x[FROM-1]
	_ = x[WHERE-2]
	_ = x[LIMIT-3]
	_ = x[OFFSET-4]
	_ = x[CREATE-5]
	_ = x[TABLE-6]
	_ = x[PRIMARY-7]
	_ = x[KEY-8]
	_ = x[UNIQUE-9]
	_ = x[INDEX-10]
	_ = x[CONSTRAINT-11]
	_ = x[FOREIGN-12]
	_ = x[NULL-13]
	_ = x[IS-14]
	_ = x[NOT-15]
	_ = x[DISTINCT-16]
	_ = x[GROUP-17]
	_ = x[BY-18]
	_ = x[WITH-19]
	_ = x[HAVING-20]
	_ = x[INNER-21]
	_ = x[LEFT-22]
	_ = x[OUTER-23]
	_ = x[JOIN-24]
	_ = x[CROSS-25]
	_ = x[VIEW-26]
	_ = x[DATABASE-27]
	_ = x[USER-28]
	_ = x[AS-29]
	_ = x[SCHEMA-30]
	_ = x[IF-31]
	_ = x[EXISTS-32]
	_ = x[BOOLEAN-33]
	_ = x[FLOAT-34]
	_ = x[REAL-35]
	_ = x[DOUBLE-36]
	_ = x[SMALLINT-37]
	_ = x[INT-38]
	_ = x[BIGINT-39]
	_ = x[VARCHAR-40]
	_ = x[CHAR-41]
	_ = x[CHARACTER-42]
	_ = x[UUID-43]
	_ = x[DATE-44]
	_ = x[TIMESTAMP-45]
	_ = x[TIME-46]
	_ = x[INTERVAL-47]
	_ = x[REGCLASS-48]
	_ = x[TEXT-49]
	_ = x[BYTEA-50]
	_ = x[NUMERIC-51]
	_ = x[DECIMAL-52]
	_ = x[DEC-53]
}

const _Word_name = "SELECTFROMWHERELIMITOFFSETCREATETABLEPRIMARYKEYUNIQUEINDEXCONSTRAINTFOREIGNNULLISNOTDISTINCTGROUPBYWITHHAVINGINNERLEFTOUTERJOINCROSSVIEWDATABASEUSERASSCHEMAIFEXISTSBOOLEANFLOATREALDOUBLESMALLINTINTBIGINTVARCHARCHARCHARACTERUUIDDATETIMESTAMPTIMEINTERVALREGCLASSTEXTBYTEANUMERICDECIMALDEC"

var _Word_index = [...]uint16{0, 6, 10, 15, 20, 26, 32, 37, 44, 47, 53, 58, 68, 75, 79, 81, 84, 92, 97, 99, 103, 109, 114, 118, 123, 127, 132, 136, 144, 148, 150, 156, 158, 164, 171, 176, 180, 186, 194, 197, 203, 210, 214, 223, 227, 231, 240, 244, 252, 260, 264, 269, 276, 283, 286}

func (i Word) String() string {
	if i >= Word(len(_Word_index)-1) {
		return "Word(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Word_name[_Word_index[i]:_Word_index[i+1]]
}
