// Code generated by "stringer -type=ReferenceAction -output=reference_action.strings.go"; DO NOT EDIT.

package tree

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Restrict-1]
	_ = x[Cascade-2]
	_ = x[SetNull-3]
	_ = x[NoAction-4]
	_ = x[SetDefault-5]
}

const _ReferenceAction_name = "RestrictCascadeSetNullNoActionSetDefault"

var _ReferenceAction_index = [...]uint8{0, 8, 15, 22, 30, 40}

func (i ReferenceAction) String() string {
	i -= 1
	if i >= ReferenceAction(len(_ReferenceAction_index)-1) {
		return "ReferenceAction(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ReferenceAction_name[_ReferenceAction_index[i]:_ReferenceAction_index[i+1]]
}
